# Generated by Django 4.1.2 on 2022-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('ar', 'статья'), ('nw', 'новость')], default='ar', max_length=2),
        ),
    ]
